# see https://docs.travis-ci.com/user/languages/r/
language: r
sudo: required
warnings_are_errors: true

r_binary_packages:
  - rgl
  - testthat
  - RANN
  - igraph
  - ff
  - bigmemory
  - filehash
  - plyr
  - spam

r_github_packages:
  - jefferis/nat

env:
  global:
    - RGL_USE_NULL=TRUE
