language: c
script: ./travis-tool.sh run_tests
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh r_binary_install rgl testthat RANN igraph ff bigmemory filehash plyr spam
  - ./travis-tool.sh install_github jefferis/nat
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get install cmtk --no-install-recommends
install:
  - ./travis-tool.sh install_deps
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    - WARNINGS_ARE_ERRORS=1
    - R_BUILD_ARGS=--no-manual
    - R_CHECK_ARGS=--no-manual --as-cran
    - _R_CHECK_FORCE_SUGGESTS_=0
    - RGL_USE_NULL=TRUE
after_success:
